// src/views/LargeTextView.tsx
import React, { useEffect, useRef, useState, useCallback } from "react";
import { listen } from "@tauri-apps/api/event";
import { getCurrentWindow } from "@tauri-apps/api/window";
import { invoke } from "@tauri-apps/api/core";
import {
  FolderOpen,
  Search,
  Edit3,
  ArrowRight,
  XCircle,
} from "lucide-react";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { ScrollArea } from "@/components/ui/scroll-area";
import { useLargeTextStore } from "@/store/largeTextStore";
import {
  openFile,
  getFileContent,
  searchFile,
  replaceText,
  // type FileInfo,
  type SearchMatch,
  closeFile,
  cleanupSessions,
} from "@/utils/textOperations";
import { message } from "@/utils/message";
import { viewOpenFile } from "@/utils/view";
import FindDialog from "@/components/FindDialog";
import ReplaceDialog from "@/components/ReplaceDialog";
import GotoDialog from "@/components/GotoDialog";

const VISIBLE_LINE_COUNT = 500;

export default function LargeTextView() {
  const lineNumberRef = useRef<HTMLDivElement>(null);
  const codeScrollbarRef = useRef<HTMLDivElement>(null);
  const [isSyncing, setIsSyncing] = useState(false);

  const {
    fileInfo,
    visibleLines,
    searchQuery,
    searchType,
    searchResults,
    totalMatches,
    currentLine,
    caseSensitive,
    useRegex,
    loading,
    showFindDialog,
    showReplaceDialog,
    showGotoDialog,
    // isLoadingLines,
    setFileInfo,
    setVisibleLines,
    setSearchQuery,
    setSearchType,
    setSearchResults,
    setTotalMatches,
    setCurrentLine,
    setCaseSensitive,
    setUseRegex,
    setLoading,
    setShowFindDialog,
    setShowReplaceDialog,
    setShowGotoDialog,
    setIsLoadingLines,
    clearSearch,
    cleanup,
  } = useLargeTextStore();

  const loadLines = useCallback(
    async (start: number, count: number) => {
      if (!fileInfo) {
        return;
      }
      setIsLoadingLines(true);
      try {
        const lines = await getFileContent({
          path: fileInfo.path,
          start_line: start + 1,
          end_line: start + count + 1,
          encoding: undefined,
        });
        setVisibleLines(
          lines.map((content, i) => ({
            number: start + i + 1,
            content,
          }))
        );
      } catch (e) {
        message(`Failed to load lines: ${e}`, { type: "error" });
      } finally {
        setIsLoadingLines(false);
      }
    },
    [fileInfo, setVisibleLines, setIsLoadingLines]
  );

  useEffect(() => {
    if (fileInfo) {
      loadLines(0, VISIBLE_LINE_COUNT);
    }
  }, [fileInfo]);

  const openFileDialog = async () => {
    try {
      const path = await viewOpenFile(false, "text", ["*"]);
      if (path) {
        const fileData = await openFile({
          path,
          encoding: undefined,
        });

        setFileInfo(fileData);
      }
    } catch (e) {
      message(`Failed to open file: ${e}`, { type: "error" });
    }
  };

  const loadFileFromPath = async (path: string) => {

    try {
      const win = getCurrentWindow();
      await win.show();
      await win.setFocus();

      const fileData = await openFile({
        path,
        encoding: undefined,
      });

      setFileInfo(fileData);
    } catch (e) {
      message(`Failed to open file: ${e}`, { type: "error" });
    }
  };

  const escapeRegExp = (str: string) => {
    return str.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
  };

  const escapeHtml = (text: string) => {
    return text
      .replace(/&/g, "&amp;")
      .replace(/</g, "&lt;")
      .replace(/>/g, "&gt;")
      .replace(/"/g, "&quot;")
      .replace(/'/g, "&#039;");
  };

  const highlightMatch = (content: string) => {
    if (!searchQuery) return escapeHtml(content);
    try {
      let regex: RegExp;
      const escapedContent = escapeHtml(content);
      if (useRegex) {
        const flags = "g" + (caseSensitive ? "" : "i");
        regex = new RegExp(`(${searchQuery})`, flags);
      } else {
        const escaped = escapeRegExp(searchQuery);
        const flags = "g" + (caseSensitive ? "" : "i");
        regex = new RegExp(`(${escaped})`, flags);
      }
      return escapedContent.replace(regex, "<mark>$1</mark>");
    } catch (e) {
      return escapeHtml(content);
    }
  };

  const isMatchLine = (lineNumber: number) => {
    return searchResults.some((m) => m.line_number === lineNumber);
  };

  const matchVisibleLines = () => {
    if (!searchQuery.trim()) {
      clearSearch();
      return;
    }
    setSearchType("visible");
    const matches: SearchMatch[] = [];
    let regex: RegExp | null = null;

    try {
      if (useRegex) {
        const flags = "g" + (caseSensitive ? "" : "i");
        regex = new RegExp(searchQuery, flags);
      } else {
        const escaped = escapeRegExp(searchQuery);
        const flags = "g" + (caseSensitive ? "" : "i");
        regex = new RegExp(escaped, flags);
      }
    } catch (e) {
      message(`matchVisibleLines failed: ${e}`, { type: "error" });
      return;
    }

    for (const line of visibleLines) {
      const content = line.content;
      let match;
      regex.lastIndex = 0;

      while ((match = regex.exec(content)) !== null) {
        matches.push({
          line_number: line.number,
          line_content: content,
          match_start: match.index,
          match_length: match[0].length,
          byte_offset: 0,
        });
      }
    }

    setSearchResults(matches);
    setTotalMatches(matches.length);

    if (matches.length < 1) {
      message("No matching content found");
    }
  };

  const searchAllFile = async () => {
    if (!fileInfo) return;

    try {
      setLoading(true);
      setSearchResults([]);

      const result = await searchFile({
        path: fileInfo.path,
        query: searchQuery,
        case_sensitive: caseSensitive,
        use_regex: useRegex,
        page: 1,
        page_size: VISIBLE_LINE_COUNT,
      });

      setSearchResults(result.matches);
      setTotalMatches(result.total_matches);

      if (result.total_matches < 1) {
        message("No matching content found");
      }
    } catch (e) {
      message(`searchAllFile failed: ${e}`, { type: "error" });
    } finally {
      setLoading(false);
    }
  };

  const doSearch = (type: "visible" | "all") => {
    setSearchType(type);
    if (type === "visible") {
      matchVisibleLines();
    } else {
      searchAllFile();
    }
  };

  const handleGotoLine = async (lineNumber: number) => {
    if (!fileInfo) return;

    const clampedLine = Math.max(
      1,
      Math.min(lineNumber, fileInfo.line_count)
    );

    setCurrentLine(clampedLine - 1);
    await loadLines(clampedLine - 1, VISIBLE_LINE_COUNT);

    if (searchQuery.trim()) {
      matchVisibleLines();
    }

    message(`Jumped to line ${clampedLine}`, { type: "success" });
  };

  const handleReplace = async (params: {
    search: string;
    replace: string;
    replaceAll: boolean;
    caseSensitive: boolean;
  }) => {
    if (!fileInfo) return;

    try {
      setLoading(true);

      const count = await replaceText({
        path: fileInfo.path,
        search_query: params.search,
        replace_text: params.replace,
        replace_all: params.replaceAll,
        case_sensitive: params.caseSensitive,
        encoding: fileInfo.encoding,
      });

      message(`Replacement completed: ${count}`, { type: "success" });

      await closeFile(fileInfo.path);

      const newFileInfo = await openFile({
        path: fileInfo.path,
        encoding: undefined,
      });

      setFileInfo(newFileInfo);
      await loadLines(currentLine, VISIBLE_LINE_COUNT);

      if (searchQuery === params.search) {
        setSearchType("visible");
        doSearch(searchType);
      }
    } catch (e) {
      message(`replace failed: ${e}`, { type: "error" });
    } finally {
      setLoading(false);
    }
  };

  const formatSize = (bytes: number) => {
    if (bytes > 1024 * 1024 * 1024)
      return `${(bytes / 1024 / 1024 / 1024).toFixed(2)} GB`;
    if (bytes > 1024 * 1024) return `${(bytes / 1024 / 1024).toFixed(2)} MB`;
    if (bytes > 1024) return `${(bytes / 1024).toFixed(2)} KB`;
    return `${bytes} B`;
  };

  const handleCodeScroll = (e: React.UIEvent<HTMLDivElement>) => {
    if (isSyncing || !lineNumberRef.current) return;
    setIsSyncing(true);

    const scrollTop = e.currentTarget.scrollTop;
    lineNumberRef.current.scrollTop = scrollTop;

    requestAnimationFrame(() => {
      setIsSyncing(false);
    });
  };

  // const handleLineNumberScroll = () => {
  //   if (isSyncing || !codeScrollbarRef.current) return;
  //   setIsSyncing(true);

  //   const scrollTop = lineNumberRef.current?.scrollTop ?? 0;
  //   codeScrollbarRef.current.scrollTop = scrollTop;

  //   requestAnimationFrame(() => {
  //     setIsSyncing(false);
  //   });
  // };

  const selectLineContent = (lineNumber: number) => {
    const lineElement = document.querySelector(
      `[data-line-number="${lineNumber}"]`
    );
    if (!lineElement) return;

    const contentSpan = lineElement.querySelector(".line-content");
    if (!contentSpan) return;

    const selection = window.getSelection();
    if (!selection) return;

    const range = document.createRange();
    range.selectNodeContents(contentSpan);

    selection.removeAllRanges();
    selection.addRange(range);
  };

  const clearFile = () => {
    cleanup();
  };

  useEffect(() => {
    const init = async () => {
      try {
        await cleanupSessions();
      } catch (e) {
        console.warn('[LargeTextView] cleanupSessions failed:', e);
      }

      try {
        const pendingPath = await invoke<string | null>("get_pending_file_path");
        if (pendingPath) {
          await loadFileFromPath(pendingPath);
        }
      } catch (e) {
        console.warn('[LargeTextView] get_pending_file_path failed:', e);
      }
    };

    init();

    const unlisten = listen<string>("open-text-file", async (event) => {
      await loadFileFromPath(event.payload);
    });

    return () => {
      unlisten.then((fn) => fn());
      cleanup();
    };
  }, []);

  return (
    <div className="flex flex-col h-full overflow-hidden">
      {/* 固定的菜单区域 */}
      <div className="flex items-center gap-1 p-2 border-b bg-white dark:bg-gray-900 z-10">
        <Button
          variant="ghost"
          size="icon"
          onClick={openFileDialog}
          title="Open File"
        >
          <FolderOpen className="h-4 w-4" />
        </Button>
        <Button
          variant="ghost"
          size="icon"
          onClick={() => setShowFindDialog(true)}
          title="Search"
        >
          <Search className="h-4 w-4" />
        </Button>
        <Button
          variant="ghost"
          size="icon"
          onClick={() => setShowReplaceDialog(true)}
          title="Replace"
        >
          <Edit3 className="h-4 w-4" />
        </Button>
        <Button
          variant="ghost"
          size="icon"
          onClick={() => setShowGotoDialog(true)}
          title="Go to Line"
        >
          <ArrowRight className="h-4 w-4" />
        </Button>
        <div className="flex-grow" />
        <Button
          variant="ghost"
          size="icon"
          onClick={clearFile}
          title="Close File"
        >
          <XCircle className="h-4 w-4" />
        </Button>
      </div>

      {/* 中间可滚动数据区域 */}
      <div className="flex flex-1 min-h-0 overflow-auto">
        <div
          ref={lineNumberRef}
          className="flex-shrink-0 w-[70px] overflow-y-auto overflow-x-hidden bg-gray-100 dark:bg-gray-800 border-r border-gray-200 dark:border-gray-700 scrollbar-hide"
        >
          <div className="w-full">
            {visibleLines.map((line) => (
              <div
                key={line.number}
                className={`flex h-6 items-center justify-end pr-3 text-sm text-gray-500 dark:text-gray-400 cursor-pointer hover:bg-gray-200 dark:hover:bg-gray-700 ${
                  isMatchLine(line.number)
                    ? "bg-yellow-200 dark:bg-yellow-800"
                    : ""
                }`}
              >
                <span onClick={() => selectLineContent(line.number)}>
                  {line.number}
                </span>
              </div>
            ))}
          </div>
        </div>

        <ScrollArea
          ref={codeScrollbarRef}
          className="flex-1 bg-white dark:bg-gray-900"
          onScroll={handleCodeScroll}
        >
          <div className="min-w-full w-max">
            {visibleLines.map((line) => (
              <div
                key={line.number}
                data-line-number={line.number}
                className={`flex h-6 items-center cursor-text hover:bg-gray-100 dark:hover:bg-gray-800 ${
                  isMatchLine(line.number)
                    ? "bg-yellow-200 dark:bg-yellow-800"
                    : ""
                }`}
              >
                <span
                  className="line-content ml-2 text-sm font-mono text-gray-800 dark:text-gray-200"
                  dangerouslySetInnerHTML={{ __html: highlightMatch(line.content) }}
                />
              </div>
            ))}
          </div>
        </ScrollArea>
      </div>

      {/* 搜索结果区域 - 仅在有结果时显示 */}
      {searchResults.length > 0 && (
        <div className="border-t p-2 max-h-[200px] overflow-y-auto bg-white dark:bg-gray-900">
          <div className="flex gap-3 mb-2">
            <Badge
              variant={searchType === "visible" ? "success" : "info"}
            >
              {totalMatches} matches {searchType === "visible" ? "(Current View)" : "(All File)"}
            </Badge>
            <div className="flex-grow" />
            <Button
              variant="outline"
              size="sm"
              onClick={clearSearch}
            >
              Clear
            </Button>
          </div>

          <div className="space-y-1">
            {searchResults.map((result, idx) => (
              <div
                key={idx}
                className="flex items-center gap-2 p-2 text-sm cursor-pointer hover:bg-gray-100 dark:hover:bg-gray-800 rounded"
                onClick={() => handleGotoLine(result.line_number)}
              >
                <span className="text-gray-500 w-12">{result.line_number}</span>
                <span className="text-gray-500 w-12">{result.match_start}</span>
                <span className="text-gray-800 dark:text-gray-200 truncate">
                  {result.line_content}
                </span>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* 固定的底部文件信息区域 */}
      <div className="border-t p-2 flex items-center justify-between bg-white dark:bg-gray-900 shrink-0">
        <div className="flex items-center gap-2 max-w-[60%] overflow-hidden">
          {fileInfo && (
            <Badge variant="secondary" className="truncate">
              {fileInfo.path}
            </Badge>
          )}
        </div>

        <div className="flex items-center gap-1 flex-shrink-0">
          {fileInfo && (
            <>
              <Badge variant="warning">{fileInfo.encoding}</Badge>
              <Badge variant="secondary">{formatSize(fileInfo.size)}</Badge>
              <Badge variant="success">{fileInfo.line_count} lines</Badge>
            </>
          )}
        </div>
      </div>

      <FindDialog
        open={showFindDialog}
        onOpenChange={setShowFindDialog}
        searchQuery={searchQuery}
        caseSensitive={caseSensitive}
        useRegex={useRegex}
        loading={loading}
        onSearchQueryChange={setSearchQuery}
        onCaseSensitiveChange={setCaseSensitive}
        onUseRegexChange={setUseRegex}
        onConfirm={doSearch}
      />

      <ReplaceDialog
        open={showReplaceDialog}
        onOpenChange={setShowReplaceDialog}
        searchQuery={searchQuery}
        loading={loading}
        onReplace={handleReplace}
      />

      <GotoDialog
        open={showGotoDialog}
        onOpenChange={setShowGotoDialog}
        totalLines={fileInfo?.line_count}
        onGoTo={handleGotoLine}
      />
    </div>
  );
}

// src/views/text/largeTextView.vue
<script setup lang="ts">
import { ref, onMounted, onUnmounted } from "vue";
import { open } from "@tauri-apps/plugin-dialog";
import { ElMessageBox } from "element-plus";
import { Document, More } from "@element-plus/icons-vue";
import { listen } from "@tauri-apps/api/event";
import { getCurrentWindow } from "@tauri-apps/api/window";
import { invoke } from "@tauri-apps/api/core";
import { useRoute } from "vue-router";
import ReplaceDialog from "@/views/text/replaceDialog.vue";
import FindDialog from "@/views/text/findDialog.vue";
import GotoDialog from "@/views/text/gotoDialog.vue";
import { message } from "@/utils/message";
import {
  openFile,
  getFileContent,
  searchFile,
  replaceText,
  type FileInfo,
  type SearchMatch,
  closeFile,
  cleanupSessions
} from "@/utils/textOperations";
import { useEncoding } from "@/store/modules/options";
import { useShortcuts } from "@/utils/globalShortcut";

const fileInfo = ref<FileInfo | null>(null);
const searchQuery = ref("");
const searchType = ref<"visible" | "all">("visible");
const searchResults = ref<SearchMatch[]>([]);
const totalMatches = ref(0);
const currentLine = ref(0);
// 内容显示行数
const VISIBLE_LINE_COUNT = 500;
const visibleLines = ref([]);

const caseSensitive = ref(false);
const useRegex = ref(false);
const loading = ref(false);
const showReplaceDialog = ref(false);
const showFindDialog = ref(false);
const showGotoDialog = ref(false);
const isLoadingLines = ref(false);

const encoding = useEncoding();
const route = useRoute();

// 打开文件
async function openFileDialog() {
  try {
    const path = await open({
      filters: [{ name: "Text", extensions: ["*"] }]
    });
    if (path) {
      fileInfo.value = await openFile({
        path: path as string,
        encoding: encoding.encoding || undefined
      });
      await loadLines(0, VISIBLE_LINE_COUNT);
    }
  } catch (error: any) {
    message(`fail to open file: ${error}`, { type: "error" });
  }
}

async function loadLines(start: number, count: number) {
  if (!fileInfo.value) return;
  isLoadingLines.value = true;
  try {
    const lines = await getFileContent({
      path: fileInfo.value.path,
      start_line: start,
      end_line: start + count,
      encoding: undefined
    });
    visibleLines.value = lines.map((content, i) => ({
      number: start + i + 1,
      content
    }));
    console.log(visibleLines.value);
  } finally {
    isLoadingLines.value = false;
  }
}

async function loadFileFromPath(path: string) {
  try {
    const win = getCurrentWindow();
    await win.show();
    await win.setFocus();

    fileInfo.value = await openFile({
      path: path,
      encoding: encoding.encoding || undefined
    });

    await loadLines(0, VISIBLE_LINE_COUNT);
  } catch (e) {
    message(`loadFileFromPath failed: ${e}`, { type: "error" });
  }
}

function doSearch(type: "visible" | "all") {
  searchType.value = type;
  if (type === "visible") {
    // 前端匹配visibleLines
    matchVisibleLines();
  } else {
    // 后端搜索整个文件
    searchAllFile();
  }
}

// 对visibleLines进行查找
function matchVisibleLines() {
  if (!searchQuery.value.trim()) {
    clearSearchResults(); // 查找为空时自动清理
    return;
  }
  searchType.value = "visible";
  const matches: SearchMatch[] = [];
  let regex: RegExp | null = null;

  try {
    if (useRegex.value) {
      const flags = "g" + (caseSensitive.value ? "" : "i");
      regex = new RegExp(searchQuery.value, flags);
    } else {
      const escaped = escapeRegExp(searchQuery.value);
      const flags = "g" + (caseSensitive.value ? "" : "i");
      regex = new RegExp(escaped, flags);
    }
  } catch (e) {
    message(`matchVisibleLines failed: ${e}`, { type: "error" });
    return;
  }

  for (const line of visibleLines.value) {
    const content = line.content;
    let match;
    regex.lastIndex = 0;

    while ((match = regex.exec(content)) !== null) {
      matches.push({
        line_number: line.number,
        line_content: content,
        match_start: match.index,
        match_length: match[0].length,
        byte_offset: 0
      });
    }
  }

  // 更新结果
  searchResults.value = matches;
  totalMatches.value = matches.length;

  if (matches.length < 1) {
    message("No matching content found");
  }
}

// 搜索整个文件
async function searchAllFile() {
  if (!fileInfo.value) return;

  try {
    loading.value = true;
    searchResults.value = [];

    const result = await searchFile({
      path: fileInfo.value.path,
      query: searchQuery.value,
      case_sensitive: caseSensitive.value,
      use_regex: useRegex.value,
      page: 1,
      page_size: VISIBLE_LINE_COUNT
    });

    searchResults.value = result.matches;
    totalMatches.value = result.total_matches;

    if (result.total_matches < 1) {
      message("No matching content found");
    }
  } catch (e) {
    message(`searchAllFile failed: ${e}`, { type: "error" });
  } finally {
    loading.value = false;
  }
}

function escapeHtml(text) {
  return text
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#039;");
}

// 高亮匹配文本
function highlightMatch(content: string) {
  if (!searchQuery.value) return escapeHtml(content);
  try {
    let regex: RegExp;
    const escapedContent = escapeHtml(content);
    if (useRegex.value) {
      // 用户输入就是正则,加上全局和大小写标志
      const flags = "g" + (caseSensitive.value ? "" : "i");
      regex = new RegExp(`(${searchQuery.value})`, flags);
    } else {
      // 普通文本搜索,转义
      const escaped = escapeRegExp(searchQuery.value);
      const flags = "g" + (caseSensitive.value ? "" : "i");
      regex = new RegExp(`(${escaped})`, flags);
    }
    return escapedContent.replace(regex, "<mark>$1</mark>");
  } catch (e) {
    // 正则无效时,不高亮
    message(`highlightMatch failed: ${e}`);
    return escapeHtml(content);
  }
}

// 转义正则特殊字符
function escapeRegExp(string: string) {
  return string.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

// 判断是否为匹配行
function isMatchLine(lineNumber: number) {
  return searchResults.value.some(m => m.line_number === lineNumber);
}

async function promptGoToLine() {
  showGotoDialog.value = !showGotoDialog.value;
}

// 跳转到指定行
async function handleGotoLine(lineNumber: number) {
  if (!fileInfo.value) return;

  const clampedLine = Math.max(
    1,
    Math.min(lineNumber, fileInfo.value.line_count)
  );

  currentLine.value = clampedLine - 1;

  await loadLines(clampedLine - 1, VISIBLE_LINE_COUNT);

  // 加载新行后重新匹配
  if (searchQuery.value.trim()) {
    matchVisibleLines();
  }

  message(`Jumped to line ${clampedLine}`, { type: "success" });
}

// 处理替换
async function handleReplace(params: {
  search: string;
  replace: string;
  replaceAll: boolean;
  caseSensitive: boolean;
}) {
  if (!fileInfo.value) return;

  try {
    loading.value = true;

    const count = await replaceText({
      path: fileInfo.value.path,
      search_query: params.search,
      replace_text: params.replace,
      replace_all: params.replaceAll,
      case_sensitive: params.caseSensitive,
      encoding: fileInfo.value.encoding
    });

    message(`Replacement completed: ${count}`, { type: "success" });

    // 清除Rust缓存并重新加载
    await closeFile(fileInfo.value.path);

    fileInfo.value = await openFile({
      path: fileInfo.value.path,
      encoding: encoding.encoding || undefined
    });

    await loadLines(currentLine.value, VISIBLE_LINE_COUNT);
    if (searchQuery.value === params.search) {
      searchType.value = "visible";
      doSearch(searchType.value); // 刷新高亮
    }
  } catch (e) {
    message(`replace falied: ${e}`, { type: "error" });
  } finally {
    loading.value = false;
  }
}

// 格式化文件大小
function formatSize(bytes: number) {
  if (bytes > 1024 * 1024 * 1024)
    return `${(bytes / 1024 / 1024 / 1024).toFixed(2)} GB`;
  if (bytes > 1024 * 1024) return `${(bytes / 1024 / 1024).toFixed(2)} MB`;
  if (bytes > 1024) return `${(bytes / 1024).toFixed(2)} KB`;
  return `${bytes} B`;
}

// 清理搜索结果
function clearSearchResults() {
  searchResults.value = [];
  totalMatches.value = 0;
  searchQuery.value = "";
}
// 完整清理
async function cleanup() {
  if (fileInfo.value) {
    try {
      await closeFile(fileInfo.value.path);
    } catch (e) {
      message(`closeFile failed: ${e}`, { type: "warning" });
    }
  }
  fileInfo.value = null;
  searchQuery.value = "";
  searchResults.value = [];
  totalMatches.value = 0;
  visibleLines.value = [];
  currentLine.value = 0;
}

useShortcuts({
  onOpenFile: () => openFileDialog(),
  onSearch: () => {
    showFindDialog.value = !showFindDialog.value;
  },
  onReplace: () => {
    showReplaceDialog.value = !showReplaceDialog.value;
  },
  onJump: () => promptGoToLine()
});

let unlisten: (() => void) | null = null;

onMounted(async () => {
  // 加载现有文件
  if (fileInfo.value) {
    await loadLines(0, VISIBLE_LINE_COUNT);
  }

  // 清理会话
  try {
    await cleanupSessions();
  } catch (e) {
    message(`cleanupSessions failed: ${e}`, { type: "warning" });
  }
  let hasLoaded = false;
  // 先查询是否有待打开的文件(防止事件丢失)
  try {
    const pendingPath = await invoke<string | null>("get_pending_file_path");
    if (pendingPath) {
      await loadFileFromPath(pendingPath);
      hasLoaded = true;
    }
  } catch (e) {
    message(`get_pending_file_path failed: ${e}`, { type: "error" });
  }

  if (!hasLoaded && route.query.file) {
    await loadFileFromPath(route.query.file as string);
  }

  // 监听Rust发送的文件打开事件
  unlisten = await listen<string>("open-text-file", async event => {
    const path = event.payload;
    console.log("=== 收到文件打开事件:", path);
    await loadFileFromPath(path);
  });

  // 检查路由query参数
  if (route.query.file) {
    await loadFileFromPath(route.query.file as string);
  }
});

onUnmounted(() => {
  if (unlisten) unlisten();
  cleanup();
});

// 单击行号选中整行
function selectLineContent(lineNumber: number) {
  const lineElement = document.querySelector(
    `[data-line-number="${lineNumber}"]`
  );
  if (!lineElement) return;

  const contentSpan = lineElement.querySelector(".line-content");
  if (!contentSpan) return;

  const selection = window.getSelection();
  if (!selection) return;

  const range = document.createRange();
  range.selectNodeContents(contentSpan);

  selection.removeAllRanges();
  selection.addRange(range);
}

const lineNumberRef = ref<HTMLElement | null>(null);
const codeScrollbarRef = ref<any>(null); // Element Plus scrollbar 实例
let isSyncing = false;
const handleCodeScroll = (event: any) => {
  if (isSyncing || !lineNumberRef.value) return;
  isSyncing = true;

  // 获取代码区域的滚动顶部距离
  // 注意：el-scrollbar 的 event 可能包含 scrollTop，或者直接访问 ref 的 wrapRef
  const scrollTop =
    event?.scrollTop ?? codeScrollbarRef.value?.wrapRef?.scrollTop ?? 0;

  lineNumberRef.value.scrollTop = scrollTop;

  // 下一帧释放锁
  requestAnimationFrame(() => {
    isSyncing = false;
  });
};

// 当行号区域滚动时（虽然用户很少直接滚行号，但为了完整性），同步代码区域
const handleLineNumberScroll = () => {
  if (isSyncing || !codeScrollbarRef.value) return;
  isSyncing = true;

  const scrollTop = lineNumberRef.value?.scrollTop ?? 0;

  // 设置 el-scrollbar 内部容器的滚动
  if (codeScrollbarRef.value.wrapRef) {
    codeScrollbarRef.value.wrapRef.scrollTop = scrollTop;
  }

  requestAnimationFrame(() => {
    isSyncing = false;
  });
};
</script>

<template>
  <div class="page-view">
    <SiliconeCard v-if="fileInfo" shadow="never">
      <div class="flex items-center gap-2 ml-1 mb-1 mt-1 mr-1">
        <el-scrollbar>
          <SiliconeTag type="info">
            {{ fileInfo.path }}
          </SiliconeTag>
        </el-scrollbar>
        <SiliconeTag v-if="fileInfo" type="warning">
          {{ fileInfo.encoding }}
        </SiliconeTag>
        <SiliconeTag type="primary">
          {{ formatSize(fileInfo.size) }}
        </SiliconeTag>
        <SiliconeTag type="success">
          {{ fileInfo.line_count }} lines
        </SiliconeTag>
        <div class="flex-grow" />
        <SiliconeTooltip>
          <template #content>
            <div class="empty-desc">
              <div class="desc-row">
                <SiliconeTag type="info">Open File</SiliconeTag>
                <SiliconeTag size="small">Ctrl + D</SiliconeTag>
              </div>
              <div class="desc-row">
                <SiliconeTag type="info">Search</SiliconeTag>
                <SiliconeTag size="small">Ctrl + F</SiliconeTag>
              </div>
              <div class="desc-row">
                <SiliconeTag type="info">Replace</SiliconeTag>
                <SiliconeTag>Ctrl + H</SiliconeTag>
              </div>
              <div class="desc-row">
                <SiliconeTag type="info">Jump</SiliconeTag>
                <SiliconeTag>Ctrl + G</SiliconeTag>
              </div>
            </div>
          </template>
          <SiliconeButton
            :loading="loading"
            text
            size="small"
            @click="openFileDialog"
          >
            <el-icon><More /></el-icon>
          </SiliconeButton>
        </SiliconeTooltip>
      </div>
    </SiliconeCard>

    <el-empty v-if="!fileInfo" :image-size="200">
      <template #image>
        <el-icon :size="200" color="#909399">
          <Document />
        </el-icon>
      </template>
      <template #description>
        <div class="empty-desc">
          <div class="desc-row">
            <SiliconeTag type="success" @click="openFileDialog">
              Open File
            </SiliconeTag>
            <SiliconeTag>Ctrl + D</SiliconeTag>
          </div>
          <div class="desc-row">
            <SiliconeTag type="info">Search</SiliconeTag>
            <SiliconeTag>Ctrl + F</SiliconeTag>
          </div>
          <div class="desc-row">
            <SiliconeTag type="info">Replace</SiliconeTag>
            <SiliconeTag>Ctrl + H</SiliconeTag>
          </div>
          <div class="desc-row">
            <SiliconeTag type="info">Jump</SiliconeTag>
            <SiliconeTag>Ctrl + G</SiliconeTag>
          </div>
          <div class="mt-6">
            <SiliconeTag>Large Text View</SiliconeTag>
          </div>
        </div>
      </template>
    </el-empty>

    <!-- 内容显示区 -->
    <div
      v-else
      class="content-wrapper flex-1 min-h-0 relative w-full flex overflow-hidden"
    >
      <div
        class="line-number-wrapper"
        ref="lineNumberRef"
        @scroll="handleLineNumberScroll"
      >
        <div class="line-number-container">
          <div
            v-for="line in visibleLines"
            :key="line.number"
            class="line-number-row"
            :class="{ match: isMatchLine(line.number) }"
          >
            <span class="line-number" @click="selectLineContent(line.number)">
              {{ line.number }}
            </span>
          </div>
        </div>
      </div>

      <el-scrollbar
        ref="codeScrollbarRef"
        class="code-content-wrapper"
        @scroll="handleCodeScroll"
      >
        <div class="content-area">
          <div
            v-for="line in visibleLines"
            :key="line.number"
            class="line-row"
            :class="{ match: isMatchLine(line.number) }"
            :data-line-number="line.number"
          >
            <span class="line-content" v-html="highlightMatch(line.content)" />
          </div>
        </div>
      </el-scrollbar>
    </div>

    <!-- 查找结果面板 -->
    <SiliconeCard v-if="searchResults.length" shadow="never">
      <div class="flex gap-3 ml-1 mt-1 mb-2 mr-1">
        <SiliconeTag :type="searchType === 'visible' ? 'success' : 'primary'">
          {{ totalMatches }} matches
          {{ searchType === "visible" ? "(Current View)" : "(All File)" }}
        </SiliconeTag>
        <div class="flex-grow" />
        <SiliconeButton
          size="small"
          type="warning"
          @click="clearSearchResults"
          text
        >
          Clear
        </SiliconeButton>
      </div>

      <SiliconeTable
        :data="searchResults"
        max-height="200"
        class="ml-1 mb-1"
        :style="{ width: 'calc(100% - 8px)' }"
      >
        <el-table-column prop="line_number" label="Line" width="80" />
        <el-table-column prop="match_start" label="Column" width="80" />
        <el-table-column prop="line_content" label="Content">
          <template #default="{ row }">
            <span
              class="search-line-content"
              @click="handleGotoLine(row.line_number)"
            >
              {{ row.line_content }}
            </span>
          </template>
        </el-table-column>
      </SiliconeTable>
    </SiliconeCard>

    <FindDialog
      v-model="showFindDialog"
      :search-query="searchQuery"
      :case-sensitive="caseSensitive"
      :use-regex="useRegex"
      :loading="loading"
      @update:search-query="searchQuery = $event"
      @update:case-sensitive="caseSensitive = $event"
      @update:use-regex="useRegex = $event"
      @confirm="doSearch"
    />

    <ReplaceDialog
      v-model="showReplaceDialog"
      :search-query="searchQuery"
      @replace="handleReplace"
      :loading="loading"
    />

    <GotoDialog
      v-model="showGotoDialog"
      :total-lines="fileInfo?.line_count"
      @go-to="handleGotoLine"
    />
  </div>
</template>

<style scoped>
:deep(.el-card__body) {
  padding: 0 !important;
}

.content-wrapper {
  display: flex;
  flex-direction: row;
  height: 100%;
  overflow: hidden;
  border-radius: 12px;
}

.line-number-wrapper {
  flex-shrink: 0;
  width: 70px;
  overflow-y: auto;
  overflow-x: hidden;
  background: #fafafa;
  border-right: 1px solid #e4e7ed;
  z-index: 10;
  scrollbar-width: none;
}

.dark .line-number-wrapper {
  background: #252525;
  border-right: 1px solid #404040;
}

.line-number-container {
  width: 100%;
}

.line-number-row {
  display: flex;
  height: 24px;
  line-height: 24px;
  white-space: pre;
}

.line-number-row.match {
  background: #fff3cd;
}
.dark .line-number-row.match {
  background: #665c00;
}

.line-number-wrapper:hover .line-number-row:hover {
  background: #f5f7fa;
}
.dark .line-number-wrapper:hover .line-number-row:hover {
  background: #3d3d3d;
}

.line-number {
  width: 100%;
  text-align: right;
  padding-right: 12px;
  color: #909399;
  user-select: none;
  cursor: pointer;
  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial,
    sans-serif;
  font-size: 14px;
}
.dark .line-number {
  color: #6b6b6b;
}

.code-content-wrapper {
  flex: 1;
  height: 100%;
  overflow: hidden;
  background: #fff;
}

.dark .code-content-wrapper {
  background: #1e1e1e;
}

.content-area {
  min-width: 100%;
  width: max-content;
}

.line-row {
  display: flex;
  height: 24px;
  line-height: 24px;
  white-space: pre;
  cursor: text;
}

.line-row.match {
  background: #fff3cd;
}
.dark .line-row.match {
  background: #665c00;
}

.line-row:hover {
  background: #f5f7fa;
}
.dark .line-row:hover {
  background: #3d3d3d;
}

.line-content {
  flex: 1;
  margin-left: 8px;
  cursor: text;
  user-select: text;
  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial,
    sans-serif;
  font-size: 14px;
  color: #303133;
}
.dark .line-content {
  color: #e0e0e0;
}

mark {
  background: #ffeb3b;
  padding: 0 2px;
  border-radius: 2px;
}
.dark mark {
  background: #ff9800;
  color: #000;
}
</style>
